spring:
  datasource:
    username: root
    password: Ndaka@2022
    url: jdbc:mysql://localhost:3306/cardb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect